### ISSUE TITLE
FilamentImageLibraryPlugin not found

### ISSUE THREAD

**Issue by faydanube** [outer-web/filament-image-library#1]
Class "OuterWeb\FilamentImageLibrary\Filament\Plugins\FilamentImageLibraryPlugin" not found

I'm lost, I followed the documentation step by step, including the installation and configuration of 'outer-web/image-library', but it keeps reporting errors, I'm not sure if it's just me?

**Comment by SimonBroekaert** [comment]
Hmm, I use this package for my personal project too, but I have not (yet) had this issue?

Just making sure:

You have `outerweb/filament-image-library` installed in your composer.json?

You have use `Outerweb\FilamentImageLibrary\Filament\Plugins\FilamentImageLibraryPlugin;` in your FilamenServiceProvider file?

Maybe a composer dump-autoload could help you?

**Comment by faydanube** [comment]
> Hello,
> 
> Hmm, I use this package for my personal project too, but I have not (yet) had this issue?
> 
> Just making sure:
> 
> You have `outerweb/filament-image-library` installed in your composer.json?
> 
> You have use `Outerweb\FilamentImageLibrary\Filament\Plugins\FilamentImageLibraryPlugin;` in your FilamenServiceProvider file?
> 
> Maybe a composer dump-autoload could help you?
> 
> Hoping you can resolve your issue!
> 
> Kind regards

thx, I'll try again later on your suggestion.

**Comment by tsalim13** [comment]
i have te same issue and the composer dump-autoload didn't resolve it

**Comment by tsalim13** [comment]
@faydanube any solution found?

**Comment by SimonBroekaert** [comment]
Hello @faydanube and @tsalim13 ,

I found the problem! Well not in code, but in the README.md

It should be `Outerweb\FilamentImageLibrary\Filament\Plugins\FilamentImageLibraryPlugin`

The readme had Outer**W**eb\FilamentImageLibrary\Filament\Plugins\FilamentImageLibraryPlugin (Note the wrongly capitalized W in my company name Outerweb.)

Sorry for the confusion! Hope this solves your issue.

You can always re-open this issue if this did not fix it.

Thank you for your patience as I am a solo developer with a main and side job.

**Comment by faydanube** [comment]
> Sorry for the confusion! Hope this solves your issue.

thx.
