### ISSUE TITLE
Unable to call component method. Public method [nextPage] not found on component

### ISSUE THREAD

**Issue by luigirossidev** [outer-web/filament-image-library#2]
Steps to reproduce:

1. Add ImageLibraryPicker to a form, with multiple() option
2. Uplaod more than 10 images
3. Click on "select_existing" button
4. Click to "Next Page" button

thanks

**Comment by SimonBroekaert** [comment]
Hi @luigirossidev ,

I came accross this issue in a personal project of mine too and fixed it in **v2.5**

So running composer update should fix this issue!

Please let me know if you find any other problems! Thank you for reporting them!
