### ISSUE TITLE
Missing method allowedDisks

### ISSUE THREAD

**Issue by markosole** [outer-web/filament-image-library#4]
I would like to report an issue with library or configuration (could be that something have changed and wasn't updated on docs).

When Filament Panel provider is configured with settings below, I get the error that `AllowedDisks` method could not be found. Which is true, it does not exist in file below.

```php
// Panel provider configuration
->plugins([
    FilamentImageLibraryPlugin::make()
      ->AllowedDisks([
            'public' => 'Public images',
        ]),
 ]),
```

#### And actual library with methods:

`vendor/outerweb/filament-image-library/src/Filament/Plugins/FilamentImageLibraryPlugin.php`

Then I have added missing method by editing core library file above and what I have noticed (thanks to Ray) that method is called very 5 seconds even if I am navigated to Dashboard and not actually using library / image picker.

```php
// added missing function
public function allowedDisks(array $disks): static
    {
        ray(">> Setting up allowed disks: ");
        ray($disks);
        $this->allowedDisks = $disks;

        return $this;
    }
```
Looks like that Filament is loading FilamentImageLibraryPlugin class every 5 seconds. Would this be normal?
I am using Laravel 11 with latest Filament. Not sure if that is related, I haven't tried it on older versions.

**Comment by SimonBroekaert** [comment]
Hi @markosole ,

Thanks for notifying me about this issue!

I have added the missing `allowedDisks()` method in **v2.6.0**, could you check?

The problem you mentioned about Filament loading the FilamentImageLibraryPlugin every 5 seconds looks to me like a Filament "issue". We use the standard way of implementing the package so I think it has something to do with the Filament internals.

I will close this issue now, but feel free to re-open if u still have problems!
